name: wbl_mobile_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  toastification: ^2.3.0
  provider: ^6.1.2
  modal_progress_hud_nsn: ^0.5.1
  flutter_svg: ^2.0.10
  image_picker: ^0.8.9
  flutter_chat_ui: ^1.6.14
  carousel_slider: ^5.0.0
  table_calendar: ^3.1.2
  googleapis: any
  googleapis_auth: any
  http: ^1.2.2
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.8
  youtube_player_flutter: ^9.1.0
  url_launcher: ^6.0.17
  shimmer: ^3.0.0
  infinite_scroll_pagination: ^4.0.0
  flutter_spinkit: ^5.1.0  # Check for the latest version
  google_fonts: ^6.2.1  # Check for the latest version
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/carousel/ML1.jpeg
    - assets/carousel/ML3.jpeg
    - assets/carousel/html-css-JS.webp
    - assets/carousel/js-libs.png
    - assets/carousel/testing-libs-JS.png
    - assets/courses/machine_learning.jpeg
    - assets/courses/fullstack_development.jpeg
    - assets/courses/data_engineer.jpg
    - assets/images/profile_icon.jpg
    - assets/images/javascript.svg
    - assets/wbl_logo.svg
    - assets/background_bottom.svg
    - assets/background_top.svg
    


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Scriptina
      fonts:
        - asset: assets/fonts/Scriptina-Regular.ttf
    - family: Southam
      fonts:
        - asset: assets/fonts/Southam.otf
    - family: Creattion
      fonts:
        - asset: assets/fonts/Creattion.otf
    - family: Sacramento
      fonts:
        - asset: assets/fonts/Sacramento-Regular.ttf
    - family: Weissenhof
      fonts:
        - asset: assets/fonts/Weissenhof-Grotesk-Regular.ttf
    - family: Arctik
      fonts:
        - asset: assets/fonts/arctik.ttf
